longitud([],0).
longitud(Lista,N):-
    Lista = [_|Col],
    longitud(Col,M),
    N is M+1.
posicion([Cabeza|_],1,Cabeza).
posicion([_|Cola],N,X):-
    N>0,
    N1 is N-1,
    posicion(Cola,N1,X1),
    X=X1.
pos(1,6).
pos(2,6).
pos(3,8).
pos(4,4).
pos(5,4).
pos(6,8).
pos(7,5).
pos(8,5).
pos(9,8).
pos(10,4).
pos(11,4).
pos(12,8).
pos(13,6).
pos(14,6).
pos(15,7).
pos(16,5).
pos(17,9).
pos(18,3).
pos(19,5).
pos(20,5).
pos(21,5).
pos(22,5).
pos(23,3).
pos(24,9).
pos(25,5).
pos(26,7).
miembro(X,[X,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]):-
  X = Lista,
  pos(1,N),
  length(Lista,N).
miembro(X,[_,X,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]):-
  X = Lista,
  pos(2,N),
  length(Lista,N).
miembro(X,[_,_,X,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]):-
  X = Lista,
  pos(3,N),
  length(Lista,N).
miembro(X,[_,_,_,X,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]):-
  X = Lista,
  pos(4,N),
  length(Lista,N).
miembro(X,[_,_,_,_,X,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]):-
  X = Lista,
  pos(5,N),
  length(Lista,N).
miembro(X,[_,_,_,_,_,X,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]):-
  X = Lista,
  pos(6,N),
  length(Lista,N).
miembro(X,[_,_,_,_,_,_,X,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]):-
  X = Lista,
  pos(7,N),
  length(Lista,N).
miembro(X,[_,_,_,_,_,_,_,X,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]):-
  X = Lista,
  pos(8,N),
  length(Lista,N).
miembro(X,[_,_,_,_,_,_,_,_,X,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]):-
  X = Lista,
  pos(9,N),
  length(Lista,N).
miembro(X,[_,_,_,_,_,_,_,_,_,X,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]):-
  X = Lista,
  pos(10,N),
  length(Lista,N).
miembro(X,[_,_,_,_,_,_,_,_,_,_,X,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]):-
  X = Lista,
  pos(11,N),
  length(Lista,N).
miembro(X,[_,_,_,_,_,_,_,_,_,_,_,X,_,_,_,_,_,_,_,_,_,_,_,_,_,_]):-
  X = Lista,
  pos(12,N),
  length(Lista,N).
miembro(X,[_,_,_,_,_,_,_,_,_,_,_,_,X,_,_,_,_,_,_,_,_,_,_,_,_,_]):-
  X = Lista,
  pos(13,N),
  length(Lista,N).
miembro(X,[_,_,_,_,_,_,_,_,_,_,_,_,_,X,_,_,_,_,_,_,_,_,_,_,_,_]):-
  X = Lista,
  pos(14,N),
  length(Lista,N).
miembro(X,[_,_,_,_,_,_,_,_,_,_,_,_,_,_,X,_,_,_,_,_,_,_,_,_,_,_]):-
  X = Lista,
  pos(15,N),
  length(Lista,N).
miembro(X,[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,X,_,_,_,_,_,_,_,_,_,_]):-
  X = Lista,
  pos(16,N),
  length(Lista,N).
miembro(X,[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,X,_,_,_,_,_,_,_,_,_]):-
  X = Lista,
  pos(17,N),
  length(Lista,N).
miembro(X,[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,X,_,_,_,_,_,_,_,_]):-
  X = Lista,
  pos(18,N),
  length(Lista,N).
miembro(X,[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,X,_,_,_,_,_,_,_]):-
  X = Lista,
  pos(19,N),
  length(Lista,N).
miembro(X,[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,X,_,_,_,_,_,_]):-
  X = Lista,
  pos(20,N),
  length(Lista,N).
miembro(X,[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,X,_,_,_,_,_]):-
  X = Lista,
  pos(21,N),
  length(Lista,N).
miembro(X,[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,X,_,_,_,_]):-
  X = Lista,
  pos(22,N),
  length(Lista,N).
miembro(X,[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,X,_,_,_]):-
  X = Lista,
  pos(23,N),
  length(Lista,N).
miembro(X,[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,X,_,_]):-
  X = Lista,
  pos(24,N),
  length(Lista,N).
miembro(X,[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,X,_]):-
  X = Lista,
  pos(25,N),
  length(Lista,N).
miembro(X,[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,X]):-
  X = Lista,
  pos(26,N),
  length(Lista,N).
ubicacion1(X,[X,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]).
ubicacion2(X,[_,X,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]).
ubicacion3(X,[_,_,X,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]).
ubicacion4(X,[_,_,_,X,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]).
ubicacion5(X,[_,_,_,_,X,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]).
ubicacion6(X,[_,_,_,_,_,X,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]).
ubicacion7(X,[_,_,_,_,_,_,X,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]).
ubicacion8(X,[_,_,_,_,_,_,_,X,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]).
ubicacion9(X,[_,_,_,_,_,_,_,_,X,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]).
ubicacion10(X,[_,_,_,_,_,_,_,_,_,X,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]).
ubicacion11(X,[_,_,_,_,_,_,_,_,_,_,X,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_]).
ubicacion12(X,[_,_,_,_,_,_,_,_,_,_,_,X,_,_,_,_,_,_,_,_,_,_,_,_,_,_]).
ubicacion13(X,[_,_,_,_,_,_,_,_,_,_,_,_,X,_,_,_,_,_,_,_,_,_,_,_,_,_]).
ubicacion14(X,[_,_,_,_,_,_,_,_,_,_,_,_,_,X,_,_,_,_,_,_,_,_,_,_,_,_]).
ubicacion15(X,[_,_,_,_,_,_,_,_,_,_,_,_,_,_,X,_,_,_,_,_,_,_,_,_,_,_]).
ubicacion16(X,[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,X,_,_,_,_,_,_,_,_,_,_]).
ubicacion17(X,[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,X,_,_,_,_,_,_,_,_,_]).
ubicacion18(X,[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,X,_,_,_,_,_,_,_,_]).
ubicacion19(X,[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,X,_,_,_,_,_,_,_]).
ubicacion20(X,[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,X,_,_,_,_,_,_]).
ubicacion21(X,[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,X,_,_,_,_,_]).
ubicacion22(X,[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,X,_,_,_,_]).
ubicacion23(X,[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,X,_,_,_]).
ubicacion24(X,[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,X,_,_]).
ubicacion25(X,[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,X,_]).
ubicacion26(X,[_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,X]).
sol(C):-
        ubicacion17([m,e,r,m,e,l,a,d,a],C),
        miembro([e,j,e],C),
        miembro([p,a,n],C),
        miembro([a,r,t,e],C),
        miembro([c,a,f,e],C),
        miembro([n,u,b,e],C),
        miembro([o,j,a,l],C),
        miembro([a,i,r,a,r],C),
        miembro([a,r,b,o,l],C),
        miembro([c,e,n,i,t],C),
        miembro([l,i,b,r,e],C),
        miembro([o,p,a,l,o],C),
        miembro([s,a,l,u,d],C),
        miembro([u,n,c,i,r],C),
        miembro([v,o,r,a,z],C),
        miembro([a,r,r,e,a,r],C),
        miembro([c,a,p,t,a,r],C),
        miembro([d,u,e,n,d,e],C),
        miembro([f,o,r,m,a,l],C),
        miembro([l,e,a,l,t,a,d],C),
        miembro([o,c,u,p,a,d,o],C),
        miembro([c,o,l,g,a,n,t,e],C),
        miembro([e,s,t,r,e,l,l,a],C),
        miembro([p,a,r,a,g,u,a,s],C),
        miembro([q,u,e,r,u,b,i,n],C),
        miembro([e,s,p,i,o,n,a,j,e],C),
        miembro([m,e,r,m,e,l,a,d,a],C),
        ubicacion1(X1,C),
        ubicacion15(Y1,C),
        nth1(2,X1,Letra1),
        nth1(1,Y1,Letra1),
        ubicacion1(X2,C),
        ubicacion17(Y2,C),
        nth1(4,X2,Letra2),
        nth1(1,Y2,Letra2),
        ubicacion1(X3,C),
        ubicacion19(Y3,C),
        nth1(6,X3,Letra3),
        nth1(1,Y3,Letra3),
        ubicacion2(X4,C),
        ubicacion21(Y4,C),
        nth1(1,X4,Letra4),
        nth1(1,Y4,Letra4),
        ubicacion2(X5,C),
        ubicacion23(Y5,C),
        nth1(3,X5,Letra5),
        nth1(1,Y5,Letra5),
        ubicacion2(X6,C),
        ubicacion25(Y6,C),
        nth1(5,X6,Letra6),
        nth1(1,Y6,Letra6),
        ubicacion3(X7,C),
        ubicacion15(Y7,C),
        nth1(2,X7,Letra7),
        nth1(3,Y7,Letra7),
        ubicacion3(X8,C),
        ubicacion17(Y8,C),
        nth1(4,X8,Letra8),
        nth1(3,Y8,Letra8),
        ubicacion3(X9,C),
        ubicacion19(Y9,C),
        nth1(6,X9,Letra9),
        nth1(3,Y9,Letra9),
        ubicacion3(X10,C),
        ubicacion21(Y10,C),
        nth1(8,X10,Letra10),
        nth1(3,Y10,Letra10),
        ubicacion4(X11,C),
        ubicacion23(Y11,C),
        nth1(1,X11,Letra11),
        nth1(3,Y11,Letra11),
        ubicacion4(X12,C),
        ubicacion25(Y12,C),
        nth1(3,X12,Letra12),
        nth1(3,Y12,Letra12),
        ubicacion5(X13,C),
        ubicacion15(Y13,C),
        nth1(2,X13,Letra13),
        nth1(5,Y13,Letra13),
        ubicacion5(X14,C),
        ubicacion17(Y14,C),
        nth1(4,X14,Letra14),
        nth1(5,Y14,Letra14),
        ubicacion6(X15,C),
        ubicacion19(Y15,C),
        nth1(1,X15,Letra15),
        nth1(5,Y15,Letra15),
        ubicacion6(X16,C),
        ubicacion21(Y16,C),
        nth1(3,X16,Letra16),
        nth1(5,Y16,Letra16),
        ubicacion6(X17,C),
        ubicacion24(Y17,C),
        nth1(5,X17,Letra17),
        nth1(1,Y17,Letra17),
        ubicacion6(X18,C),
        ubicacion25(Y18,C),
        nth1(7,X18,Letra18),
        nth1(5,Y18,Letra18),
        ubicacion7(X19,C),
        ubicacion15(Y19,C),
        nth1(2,X19,Letra19),
        nth1(7,Y19,Letra19),
        ubicacion7(X20,C),
        ubicacion17(Y20,C),
        nth1(4,X20,Letra20),
        nth1(7,Y20,Letra20),
        ubicacion8(X21,C),
        ubicacion24(Y21,C),
        nth1(2,X21,Letra21),
        nth1(3,Y21,Letra21),
        ubicacion8(X22,C),
        ubicacion26(Y22,C),
        nth1(4,X22,Letra22),
        nth1(1,Y22,Letra22),
        ubicacion9(X23,C),
        ubicacion16(Y23,C),
        nth1(2,X23,Letra23),
        nth1(1,Y23,Letra23),
        ubicacion9(X24,C),
        ubicacion17(Y24,C),
        nth1(4,X24,Letra24),
        nth1(9,Y24,Letra24),
        ubicacion9(X25,C),
        ubicacion20(Y25,C),
        nth1(6,X25,Letra25),
        nth1(1,Y25,Letra25),
        ubicacion9(X26,C),
        ubicacion22(Y26,C),
        nth1(8,X26,Letra26),
        nth1(1,Y26,Letra26),
        ubicacion10(X27,C),
        ubicacion24(Y27,C),
        nth1(1,X27,Letra27),
        nth1(5,Y27,Letra27),
        ubicacion10(X28,C),
        ubicacion26(Y28,C),
        nth1(3,X28,Letra28),
        nth1(3,Y28,Letra28),
        ubicacion11(X29,C),
        ubicacion16(Y29,C),
        nth1(2,X29,Letra29),
        nth1(3,Y29,Letra29),
        ubicacion11(X30,C),
        ubicacion18(Y30,C),
        nth1(4,X30,Letra30),
        nth1(1,Y30,Letra30),
        ubicacion12(X31,C),
        ubicacion20(Y31,C),
        nth1(1,X31,Letra31),
        nth1(3,Y31,Letra31),
        ubicacion12(X32,C),
        ubicacion22(Y32,C),
        nth1(3,X32,Letra32),
        nth1(3,Y32,Letra32),
        ubicacion12(X33,C),
        ubicacion24(Y33,C),
        nth1(5,X33,Letra33),
        nth1(7,Y33,Letra33),
        ubicacion12(X34,C),
        ubicacion26(Y34,C),
        nth1(7,X34,Letra34),
        nth1(5,Y34,Letra34),
        ubicacion13(X35,C),
        ubicacion16(Y35,C),
        nth1(2,X35,Letra35),
        nth1(5,Y35,Letra35),
        ubicacion13(X36,C),
        ubicacion18(Y36,C),
        nth1(4,X36,Letra36),
        nth1(3,Y36,Letra36),
        ubicacion13(X37,C),
        ubicacion20(Y37,C),
        nth1(6,X37,Letra37),
        nth1(5,Y37,Letra37),
        ubicacion14(X38,C),
        ubicacion22(Y38,C),
        nth1(1,X38,Letra38),
        nth1(5,Y38,Letra38),
        ubicacion14(X39,C),
        ubicacion24(Y39,C),
        nth1(3,X39,Letra39),
        nth1(9,Y39,Letra39),
        ubicacion14(X40,C),
        ubicacion26(Y40,C),
        nth1(5,X40,Letra40),
        nth1(7,Y40,Letra40).