
package Vista;

import Controlador.Controlador;

import Modelo.Grilla;

import java.awt.*;

import java.util.ArrayList;
import java.util.Iterator;

import javax.swing.JTextField;

/**
 *
 * @author martin
 */
public class VentanaGratis extends javax.swing.JFrame implements InterfaceGratis
{
    private int alto, ancho;
    private ArrayList<JTextField> lista = new ArrayList<JTextField>();
    private Grilla grilla;
    
    /** Creates new form VentanaGratis */
    public VentanaGratis(int alto, int ancho, Grilla grilla)
    {
        initComponents();
        this.alto = alto;
        this.ancho = ancho;
        this.grilla = grilla;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jLabelTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonAceptar = new javax.swing.JButton();
        jPanelGrilla = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitulo.setText("Ingrese la primer palabra");

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGrillaLayout = new javax.swing.GroupLayout(jPanelGrilla);
        jPanelGrilla.setLayout(jPanelGrillaLayout);
        jPanelGrillaLayout.setHorizontalGroup(
            jPanelGrillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelGrillaLayout.setVerticalGroup(
            jPanelGrillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jButtonAceptar)))
                .addContainerGap(135, Short.MAX_VALUE))
            .addComponent(jPanelGrilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelGrilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAceptar)
                .addContainerGap())
        );

        pack();
    }//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelGrilla;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setControlador(Controlador controlador) {
        this.jButtonAceptar.addActionListener(controlador);
        this.jButtonAceptar.setActionCommand(InterfaceGratis.ACEPTAR);
    }

    @Override
    public void arrancar() {
        this.jPanelGrilla.setLayout(new GridLayout(alto, ancho));
        this.setMatriz();
        this.setVisible(true);
    }

    @Override
    public void matar() {
        this.dispose();
    }
    
    private void setMatriz()
    {
        for (int i = 0; i < this.alto; i++)
        {
            for (int j = 0; j < this.ancho; j++)
            {
                JTextField nuevo = new JTextField();
                this.lista.add(nuevo);
                this.jPanelGrilla.add(nuevo);
                if(this.grilla.getCelda(i, j))
                {
                    nuevo.setEditable(true);
                }else
                {
                    nuevo.setEditable(false);
                    nuevo.setBackground(Color.black);
                }
            }
        }
    }

    @Override
    public ArrayList<JTextField> getTextField()
    {
        return this.lista;
    }
}
